# Generated by Django 3.0.3 on 2020-03-15 22:56

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('todoapp', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='todoapp',
            name='reason',
            field=models.TextField(default='null'),
        ),
        migrations.AlterField(
            model_name='todoapp',
            name='start_time',
            field=models.DateTimeField(default=datetime.datetime(2020, 3, 15, 23, 56, 45, 58083)),
        ),
    ]
